name: CI - App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
        working-directory: ./app
      - name: Build
        run: npm run build
        working-directory: ./app
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"
          PROJECT_PATH: "./app"
